.TH FTSDF 1 "May 2022" "Freetype 2.12.1"
.
.
.SH NAME
.
ftsdf \- an SDF viewer
.
.
.SH SYNOPSIS
.
.B ftsdf
.I pt font
.
.
.SH DESCRIPTION
.
.B ftsdf
displays Signed Distance Fields (SDF) for glyphs of the given font, allowing
to change various rendering and display options interactively.
.
.TP
.B pt
The point size.
Since currently the resolution is always set to 72dpi, this directly gives
the ppem value (pixels per EM), too.
.
.TP
.B font
The font file to display.
.
.\" eof
